/* Logan Kim */
/* COMP228-006 */
/* Lab 2 */
/** Exercise 2:
 * Design a Lotto class with one array instance variable to hold three random integer values
 * (from 1 to 9). Include a constructor that randomly populates the array for a lotto object.
 * Also, include a method in the class to return the array.
 *
 * Use this class to simulate a simple lotto game in which the user chooses a number between
 * 3 and 27. The user runs the lotto up to 5 times and each time the sum of lotto numbers is
 * calculated. If the number chosen by the user matches the sum, the user wins and the game ends.
 * If the number does not match the sum within five rolls, the computer wins. Use methods of
 * JOptionPane class to interact with the user.
 */
package application;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

public class Lotto {
	// field arrays
	private int[][] _lottoNum = new int[5][3];
	private int[] _sum = new int[5];
	private List<String> _finalMessageArray = new ArrayList<String>();

	// max and min for random value
	private int _max = 9;
	private int _min = 1;

	// field variable for an user input
	private String _guess;
	private int _guessInt;

	// messages
	private String _intro = "Welcome to LottoWorld!"
			+ "\nNow you will have 5 chances to win the Lotto."
			+ "\nWhat you need to do is just to enter an integer between 3 - 27."
			+ "\nIf your number is matched with the Lotto number generated by computer, then you will win!"
			+ "\nHowever, if your numbers are different from the Lotto number for 5 times, then you will lose."
			+ "\nGood luck! Hit Ok to proceed!\n";
	private String _winMessage = "Congratulation! You Won the Lotto!";
	private String _wrongMessage = "Oops! Your guess was wrong.";
	private String _loseMessage = "You lost. Maybe next time!";
	private String _errorMessage = "You should enter an integer between 3 and 27! Try again!";
	private String _resultFormat = " Trial #  |        Lotto #        |  Your Guess"
			+ "\n--------------------------------";
	private String delimiter = "";

	// field variables
	private String _questionMessage;
	private String _finalMessage;

	// main
	public static void main(String[] args)
	{
		// creating an object for lotto method
		Lotto obj = new Lotto();

		// calling lotto method
		obj.lotto();
	} // end main

	// method for lotto
	private void lotto()
	{
		// declare counter for the turn
		int counter;

		// display intro
		JOptionPane.showMessageDialog(null, _intro);

		// loop for each of 5 turns
		for (counter = 0; counter < 5 ; )
		{
			// generate random value between 1 - 9 and assign it in an array
			for(int i = 0; i < 3; i++)
			{
				int number = (int) (Math.random() * (_max - _min + 1) + 1);
				_lottoNum[counter][i] = number;
			} // end for

			// calculate sum and assign it to an array
			_sum[counter] = _lottoNum[counter][0] + _lottoNum[counter][1] + _lottoNum[counter][2];

			// print question and change user input form from string to integer
			_questionMessage = "What is your guess #" + (counter + 1) + "?";
			_guess = JOptionPane.showInputDialog(_questionMessage);
			_guessInt = Integer.parseInt(_guess);

			// check if user input is between 3 and 27
			if(_guessInt >= 3 && _guessInt <=27)
			{
				// initialize a format of string for an each result and assign it in an array
				_finalMessage = String.format("\n    %02d     |  %d + %d + %d = %02d  |        %02d", (counter + 1), _lottoNum[counter][0], _lottoNum[counter][1], _lottoNum[counter][2], _sum[counter], _guessInt);
				_finalMessageArray.add(_finalMessage);

				// print if user win
				if(_guessInt == _sum[counter])
				{
					JOptionPane.showMessageDialog(null, _winMessage);
					JOptionPane.showMessageDialog(null, _winMessage + "\n" + _resultFormat + String.join(delimiter, _finalMessageArray));

					// exit program
					System.exit(0);
				} // end if
				// print if user's answer does not match with the lotto
				else
				{
					JOptionPane.showMessageDialog(null, _wrongMessage);
				} // end else

				// move to next question
				counter++;
			} // end if
			// wrong user input
			else
			{
				// tell user that input should be between 3 and 27
				JOptionPane.showMessageDialog(null, _errorMessage);
			} // end else
		} // end for

		// printing result when computer win
		JOptionPane.showMessageDialog(null, _loseMessage + "\n" + _resultFormat + String.join(delimiter,_finalMessageArray));

		// exit program
		System.exit(0);
	} // end lotto method
} // end class